config/routes.rb
Rails.application.routes.draw do
  resources :teachers
  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:edit, :update]
  def index
    @teachers = Teacher.all
  end

  def edit
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    respond_to do |format|
      if @teacher.save
        format.html { redirect_to teachers_url, notice: "Teacher was successfully saved." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to teachers_url, notice: "Teacher was successfully saved." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  def teacher_params
    params.require(:teacher).permit(:name, :email, :tel)
  end

  def set_teacher
    @teacher = Teacher.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Timely</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/timetable">Timetables</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="/configuration" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Configuration
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="/school-details">School Details</a></li>
            <li><a class="dropdown-item" href="/teachers">Teachers</a></li>
            <li><a class="dropdown-item" href="/subjects">Subjects</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="/classes">Classes</a></li>
          </ul>
        </li>
      </ul>
      <%# <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timely</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render('layouts/navbar') %>

    <div class="p-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/teachers/_form.html.erb
<%= form_with(model: teacher , local: true) do |form| %>
    <% if teacher.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

        <ul>
            <% teacher.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <div class="mb-3">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
        <%= form.label :email, class: "form-label"  %>
        <%= form.email_field :email, class: "form-control" %>
    </div>

    <div class="mb-3">
        <%= form.label :tel, class: "form-label"  %>
        <%= form.telephone_field :tel, class: "form-control" %>
    </div>

    <div class="actions">
        <%= form.submit :class => 'btn btn-primary' %>
        <%= link_to 'Back', teachers_path, :class => 'btn btn-secondary' %>
    </div>
<% end %>

app/views/teachers/edit.html.erb
<h3>Teacher Details</h3>

<%= render "form", teacher: @teacher %>

app/views/teachers/index.html.erb
<h2>Teachers</h2>
<%= link_to 'Add New Teacher', new_teacher_path, :class => 'btn btn-primary' %>

<p/>

<% if notice %>
<div class="alert alert-info alert-dismissible fade show" role="alert">
  <strong>Success!</strong> <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

<p/>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Telephone</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @teachers.each do |teacher| %>
    <tr>
      <th scope="row"><%= teacher.id %></th>
      <td><%= teacher.name %></td>
      <td><%= teacher.email %></td>
      <td><%= teacher.tel %></td>
      <td align="right"> 
        <%= link_to 'Edit', edit_teacher_path(teacher), :class => 'btn btn-secondary' %> 
        <%= link_to 'Delete', teacher, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %> 
      </td>
      
    </tr>
    <% end %>
  </tbody>
</table>

app/views/teachers/new.html.erb
<h3>Add New Teacher</h3>

<%= render "form", teacher: @teacher %>

app/views/welcome/index.html.erb
<h1>
Timely Smart Timetable Generator
</h1>